import { BuildingModel } from '../model/index'
export const BUILDINGS: BuildingModel[]=[
  new BuildingModel("city-hall", "city-hall")
    .setSize("MEDIUM")
    .setMap("app/img/maps/city-hall.png")
    .setIcon("app/img/icons/city-hall.png")
    .setImage("app/img/images/city-hall.png")
    .setEconomy(1)
    .setLoyalty(1)
    .setStability(1)
    .setPrice(11),
  new BuildingModel("noble-house", "noble-house")
    .setMap("app/img/maps/noble-house.png")
    .setIcon("app/img/icons/noble-house.png")
    .setEconomy(1)
    .setStability(1)
    .setLoyalty(1)
    .setPrice(24),
  new BuildingModel("house", "house")
    .setMap("app/img/maps/house.png")
    .setIcon("app/img/icons/house.png")
    .setPrice(2),
  new BuildingModel("castle", "castle")
    .setSize("LARGE")
    .setMap("app/img/maps/castle.png")
    .setIcon("app/img/icons/castle.png")
    .setEconomy(2)
    .setLoyalty(2)
    .setStability(2)
    .setDefence(8)
    .setPrice(54),
  new BuildingModel("garrison", "garrison")
    .setSize("MEDIUM")
    .setMap("app/img/maps/garrison.png")
    .setIcon("app/img/icons/garrison.png")
    .setLoyalty(1)
    .setStability(1)
    .setPrice(28),
  new BuildingModel("barracks", "barracks")
    .setMap("app/img/maps/barracks.png")
    .setIcon("app/img/icons/barracks.png")
    .setDefence(2)
    .setPrice(6),
  new BuildingModel("watchtower", "watchtower")
    .setMap("app/img/maps/watchtower.png")
    .setIcon("app/img/icons/watchtower.png")
    .setStability(1)
    .setDefence(2),
  new BuildingModel("wooden-wall", "wooden-wall")
    .setIcon("app/img/icons/wooden-wall.png")
    .setDefence(4)
    .setPrice(8),
  new BuildingModel("dock", "dock")
    .setMap("app/img/maps/dock.png")
    .setIcon("app/img/icons/dock.png")
    .setEconomy(1)
    .setStability(1)
    .setValue(1000)
    .setPrice(16),
  new BuildingModel("dump", "dump")
    .setMap("app/img/maps/dump.png")
    .setIcon("app/img/icons/dump.png")
    .setLoyalty(1)
    .setStability(1)
    .setPrice(6),
  new BuildingModel("healer", "healer")
    .setMap("app/img/maps/healer.png")
    .setIcon("app/img/icons/healer.png")
    .setLoyalty(1)
    .setStability(1)
    .setMinorMagicObject(1)
    .setPrice(10),
  new BuildingModel("school", "school")
    .setMap("app/img/maps/school.png")
    .setIcon("app/img/icons/school.png")
    .setEconomy(1)
    .setLoyalty(1)
    .setPrice(6),
  new BuildingModel("weaver", "weaver")
    .setMap("app/img/maps/weaver.png")
    .setIcon("app/img/icons/weaver.png")
    .setImage("app/img/images/weaver.png")
    .setEconomy(1)
    .setStability(1)
    .setPrice(6),
  new BuildingModel("sawmill", "sawmill")
    .setMap("app/img/maps/sawmill.png")
    .setIcon("app/img/icons/sawmill.png")
    .setEconomy(1)
    .setStability(1),
  new BuildingModel("blacksmith", "blacksmith")
    .setMap("app/img/maps/blacksmith.png")
    .setIcon("app/img/icons/blacksmith.png")
    .setEconomy(1)
    .setStability(1)
    .setPrice(6),
  new BuildingModel("forge", "forge")
    .setMap("app/img/maps/forge.png")
    .setIcon("app/img/icons/forge.png")
    .setEconomy(1)
    .setStability(1)
    .setValue(500)
    .setPrice(8),
  new BuildingModel("exotic-craftsman", "exotic-craftsman")
    .setMap("app/img/maps/exotic-craftsman.png")
    .setIcon("app/img/icons/exotic-craftsman.png")
    .setLoyalty(1)
    .setStability(1)
    .setMinorMagicObject(1)
    .setPrice(10),
  new BuildingModel("brewery", "brewery")
    .setMap("app/img/maps/brewery.png")
    .setIcon("app/img/icons/brewery.png")
    .setLoyalty(1)
    .setStability(1)
    .setPrice(6),
  new BuildingModel("mill", "mill")
    .setMap("app/img/maps/mill.png")
    .setIcon("app/img/icons/mill.png")
    .setEconomy(1)
    .setStability(1),
  new BuildingModel("inn", "inn")
    .setMap("app/img/maps/inn.png")
    .setIcon("app/img/icons/inn.png")
    .setEconomy(1)
    .setLoyalty(1)
    .setValue(500),
  new BuildingModel("tavern", "tavern")
    .setMap("app/img/maps/tavern.png")
    .setIcon("app/img/icons/tavern.png")
    .setEconomy(1)
    .setLoyalty(1)
    .setValue(500)
    .setPrice(12),
  new BuildingModel("trade-fair", "trade-fair")
    .setSize("MEDIUM")
    .setMap("app/img/maps/trade-fair.png")
    .setIcon("app/img/icons/trade-fair.png")
    .setEconomy(2)
    .setStability(2)
    .setValue(2000)
    .setMinorMagicObject(2)
    .setPrice(48),
  new BuildingModel("shop", "shop")
    .setMap("app/img/maps/shop.png")
    .setIcon("app/img/icons/shop.png")
    .setEconomy(1)
    .setStability(1)
    .setValue(1)
    .setPrice(8),
  new BuildingModel("granary", "granary")
    .setMap("app/img/maps/granary.png")
    .setIcon("app/img/icons/granary.png")
    .setLoyalty(1)
    .setStability(1)
    .setPrice(6),
  new BuildingModel("stable", "stable")
    .setMap("app/img/maps/stable.png")
    .setIcon("app/img/icons/stable.png")
    .setEconomy(1)
    .setLoyalty(1)
    .setValue(500)
    .setPrice(10),
  new BuildingModel("sanctuary-erastil", "sanctuary-erastil")
    .setMap("app/img/maps/sanctuary-erastil.png")
    .setIcon("app/img/icons/sanctuary-erastil.png")
    .setLoyalty(1)
    .setPrice(8),
  new BuildingModel("sanctuary-sarenrae", "sanctuary-sarenrae")
    .setMap("app/img/maps/sanctuary-sarenrae.png")
    .setIcon("app/img/icons/sanctuary-sarenrae.png")
    .setLoyalty(1)
    .setMinorMagicObject(1)
    .setPrice(8),
  new BuildingModel("temple-sarenrae", "temple-sarenrae")
    .setSize("MEDIUM")
    .setMap("app/img/maps/temple-sarenrae.png")
    .setIcon("app/img/icons/temple-sarenrae.png")
    .setLoyalty(2)
    .setStability(2)
    .setMinorMagicObject(2)
    .setPrice(8),
  new BuildingModel("graveyard", "graveyard")
    .setMap("app/img/maps/graveyard.png")
    .setIcon("app/img/icons/graveyard.png")
    .setLoyalty(1)
    .setPrice(4),
  new BuildingModel("magic-academy", "magic-academy")
    .setSize("LARGE")
    .setMap("app/img/maps/magic-academy.png")
    .setIcon("app/img/icons/magic-academy.png")
    .setEconomy(2)
    .setLoyalty(2)
    .setMinorMagicObject(3)
    .setMediumMagicObject(2)
    .setPrice(52),
  new BuildingModel("statue", "statue")
    .setMap("app/img/maps/statue.png")
    .setIcon("app/img/icons/statue.png")
    .setLoyalty(3)
    .setPrice(6),
  new BuildingModel("park", "park")
    .setMap("app/img/maps/park.png")
    .setIcon("app/img/icons/park.png")
    .setLoyalty(1)
    .setPrice(4)
]